In [0]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [0]:
iris_data = pd.read_csv('/Workspace/Users/pubudu.piyumalmv@gmail.com/Data Folder/Datasets/Iris Dataset.csv')

In [0]:
iris_data.head()

In [0]:
iris_data.info()

In [0]:
iris_data.describe()

In [0]:
iris_data.isnull()

In [0]:
iris_data.duplicated()

Exploritary Data Analys

In [0]:
display(iris_data.describe())

In [0]:
sns.pairplot(iris_data, hue='Species')
plt.title('Pairplot')
plt.show()

Machine Learning Model

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [0]:
x = iris_data.drop('Species', axis=1)
y = iris_data['Species']

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [0]:
print(confusion_matrix(y_test, y_pred))

In [0]:
print(classification_report(y_test, y_pred))

## Model Performance Analysis

### Overall Accuracy: 100%
The RandomForestClassifier achieved perfect classification on the test set (30 samples).

### Confusion Matrix Breakdown:
```
[[10  0  0]   ← Iris-setosa: 10 correct, 0 misclassified
 [ 0  9  0]   ← Iris-versicolor: 9 correct, 0 misclassified
 [ 0  0 11]]  ← Iris-virginica: 11 correct, 0 misclassified
```

### Key Metrics (all species):
* **Precision**: 1.00 - When the model predicts a species, it's correct 100% of the time
* **Recall**: 1.00 - The model finds 100% of each species in the test set
* **F1-Score**: 1.00 - Perfect balance between precision and recall

### What This Means:
* **Zero false positives**: No samples incorrectly labeled as a species they're not
* **Zero false negatives**: No samples missed or misclassified
* **Robust separation**: The model learned clear decision boundaries between all three species

### Model Configuration:
* Algorithm: Random Forest (ensemble of decision trees)
* Train/Test Split: 80/20 (120 training samples, 30 test samples)
* Random State: 42 (ensures reproducibility)
* Features Used: SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm